version: "3.9"
services:
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      # - ${PWD}/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      # - ${PWD}/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      # - ${PWD}/grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/data:/var/lib/grafana
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
